### ISSUE TITLE
possible spelling errors in Henryk Robak testimony

### ISSUE THREAD

**Issue by ChayaRNove** [YiddishCorpus/CSYE-Transcripts#1]
I noticed several possible spelling errors in [Henryk Robak's](url) testimony (tapes 1 and 2): 
- **am merstn** and **a khuts** (both of these should be one word)
- **kombadantn** (should be kombatantn based on context)

**Comment by ibleaman** [comment]
Resolved w/ https://github.com/YiddishCorpus/CSYE-Transcripts/issues/2
