### ISSUE TITLE
✏️ [CORRECTION] - <title>

### ISSUE THREAD

**Issue by Philyoniy** [YiddishCorpus/CSYE-Transcripts#4]
### Testimony

Henryk Robak

### Tape(s)

1

### Typo or mistranscription

* (איז UNK) ליטע

* נישט קײן ־קאָשעדיקן,

### Correction

BO ליטע

נישט קײן קשהדיקן,

**Comment by ibleaman** [comment]
אַ דאַנק!
aa794c4e985ee7621b3e208ea79eac04e91d58b2
